### ISSUE TITLE
pogdesign error

### ISSUE THREAD

**Issue by pr0xee** [rafakob/service.pogdesign.sync#1]
Hi there! first i would like to say "thank you" for creating the plugin. I've imported the zip file following your indications, but then i open kodi and an error arise > http://pastebin.com/QssQ9Km2

I believe i did everything like requested so i would like your help to understand the error.

thank you!

**Comment by rafakob** [comment]
Hello,
I'm glad that you like my little addon. Honestly I had no idea that someone is actually using it :)

I've managed to fix the error. The problem was obvious - I wasn't checking if TV library contains any 'watched' episodes. In that case I was performing operations on empty array which Python doesn't really like :) It's fixed now so go ahead and download it once again. Remeber to uninstall old version and restart Kodi after. If you find any other problems, let me know.

I'd love to finish this plugin 'in a right way' - with Kodi graphical interface etc. Unfortunately I don't have too much free time so it has to stay as it is. But I gotta say that I'm using it on my home media center and it works flawlessly.
